INSERT INTO "PLAYER" (ID, NAME, CREATED_DATE) VALUES(1, 'Doink', TO_DATE('2017-02-11', 'yyyy-mm-dd'));
INSERT INTO "PLAYER" (ID, NAME, CREATED_DATE) VALUES(2, 'Hercules', TO_DATE('2017-02-12', 'yyyy-mm-dd'));
INSERT INTO "PLAYER" (ID, NAME, CREATED_DATE) VALUES(3, 'Xena', TO_DATE('2017-02-13', 'yyyy-mm-dd'));